import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <p>
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quae labore
      dolore perferendis soluta a quisquam culpa aspernatur dicta optio, quidem
      blanditiis distinctio vitae officiis facere veritatis nam nihil animi.
      Doloribus.
    </p>
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div className="pt-32">{children}</div>

        <LoginModal />
        <SignupModal />
      </body>
    </html>
  );
}
